version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - your-network-name

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - your-network-name

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://root:example@localhost:27017
    networks:
      - your-network-name

networks:
  your-network-name:
